### ISSUE TITLE
Doesn't work correctly with M1 simulators

### ISSUE THREAD

**Issue by Bringoff** [flutter-fast-kit/fk_user_agent#4]
The library detects if it's a simulator by checking devices' architecture, but simulators on M1 Macs have arm64 architecture, so the library crashes the app. Can be reproduced with example project.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/5401536/135973177-f411f115-311d-43d7-87d9-cc93918f2f73.png">

**Comment by TheGlorySaint** [comment]
@simman Could you please look and review the linked PR and merge it?
